### ISSUE TITLE
training script fails to run

### ISSUE THREAD

**Issue by MaxBrandtner** [omerbt/Text2LIVE#11]
Apparently pytorch fails to allocate the required ram

```
/home/maximilian/.local/lib/python3.10/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):                                   
  File "/home/maximilian/Documents/git/Text2LIVE/train_video.py", line 102, in <module>
    train_model(config)
  File "/home/maximilian/Documents/git/Text2LIVE/train_video.py", line 28, in train_model
    dataset = AtlasDataset(config)
  File "/home/maximilian/Documents/git/Text2LIVE/datasets/video_dataset.py", line 57, in __init__
    self.background_reconstruction = reconstruct_video_layer(original_background_all_uvs, background_atlas_model)
  File "/home/maximilian/.local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/maximilian/Documents/git/Text2LIVE/util/atlas_utils.py", line 143, in reconstruct_video_layer
    rgb = (atlas_model(uv_values[frame].reshape(-1, 2)) + 1) * 0.5
  File "/home/maximilian/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/maximilian/Documents/git/Text2LIVE/models/implicit_neural_networks.py", line 80, in forward
    x = F.relu(x)
  File "/home/maximilian/.local/lib/python3.10/site-packages/torch/nn/functional.py", line 1442, in relu
    result = torch.relu(input)
RuntimeError: CUDA out of memory. Tried to allocate 324.00 MiB (GPU 0; 5.78 GiB total capacity; 1.37 GiB already allocated; 250.06 MiB free; 1.65 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by RafailFridman** [comment]
As I can see, your GPU has only 5.78GB. With the current implementation, it is certainly not enough to train the method on a video. In our experiments, we used Tesla V100 with 32GB of memory.

**Comment by MaxBrandtner** [comment]
Is there a way to run the model with less VRAM (lets say by offloading to ram or swap), or could you release the trained model? (see #11)
