### ISSUE TITLE
It's isn't working

### ISSUE THREAD

**Issue by CodeSame** [omerbt/Text2LIVE#16]
Output of powershell after command  python train_image.py --example_config golden_horse.yaml:
```
Traceback (most recent call last):
  File "C:\Users\CodeSame\miniconda3\text2live\train_image.py", line 129, in <module>
    train_model(config)
  File "C:\Users\CodeSame\miniconda3\text2live\train_image.py", line 24, in train_model
    seed = np.random.randint(2 ** 32)
  File "mtrand.pyx", line 763, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1336, in numpy.random._bounded_integers._rand_int32
ValueError: high is out of bounds for int32
```
 On my own, I was able to run this neural network by replacing in the 24th line of the file train_image.py the value from seed = np.random.randint(2** 32) to seed = np.random.randint(2** 31). BUT now all the other errors remain in the output. You can specify specific software versions and PC system requirements, if any.

**Comment by Merkoso** [comment]
I have the same. I handled with 32bit issue but now it just show me some CUDA error, I sync up my torch with CUDA Toolkit but still same situation. Probably, 32gb Tesla isn't fun recommendation, it is in must need :D

**Comment by Amazingldl** [comment]
> I have the same. I handled with 32bit issue but now it just show me some CUDA error, I sync up my torch with CUDA Toolkit but still same situation. Probably, 32gb Tesla isn't fun recommendation, it is in must need :D

same

**Comment by Pythonpa** [comment]
Does this have to be a 32GB video card? Has anyone tried 16G? Tesla T4?
