### ISSUE TITLE
Nothing happened after I modified log_images_freq in "image_config.yaml" and bootstrap_epoch: in "golden_horse.yaml" and "ice_cake.yaml".

### ISSUE THREAD

**Issue by BenoitKAO** [omerbt/Text2LIVE#17]
Thank you for your marvelous work.

However, no result by performing 'Run examples'.
~~~
Run examples
...
Video Editing
...
python train_video.py --example_config car-turn_winter.yaml

Image Editing
...
python train_image.py --example_config golden_horse.yaml

Intermediate results will be saved to results during optimization. The frequency of saving intermediate results is indicated in the log_images_freq flag of the configuration.
~~~

Nothing happened after I modified log_images_freq in "image_config.yaml" and bootstrap_epoch: in "golden_horse.yaml" and "ice_cake.yaml".
~~~
python train_image.py --example_config golden_horse.yaml
python train_image.py --example_config ice_cake.yaml
~~~

Any help is appreciated.

**Comment by BenoitKAO** [comment]
After re-installing using pip install -r requirements.txt.

Errors occurred:
~~~
Traceback (most recent call last):
  File "train_image.py", line 131, in <module>
    train_model(config)
  File "train_image.py", line 38, in train_model
    criterion = LossG(config, clip_extractor)
  File "/Text2LIVE/util/losses.py", line 18, in __init__
    self.src_e = clip_extractor.get_text_embedding(cfg["src_text"], template)
  File "/Text2LIVE/models/clip_extractor.py", line 112, in get_text_embedding
    embedding = self.model.encode_text(
  File "/Text2LIVE/CLIP/clip/model.py", line 391, in encode_text
    x = self.token_embedding(text).type(self.dtype)  # [batch_size, n_ctx, d_model]
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2044, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
~~~

Any help is appreciated.

**Comment by BenoitKAO** [comment]
I answer my question by myself.
[The adjustment depends on your GPU(s).](https://github.com/omerbt/Text2LIVE/issues/8)
I modified source codes for training my custom datasets on multiple GPUs.
